# Generated by Django 3.1.7 on 2021-04-10 02:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210410_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='demovid',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
