# Generated by Django 3.1.7 on 2021-04-10 04:42

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to=Blog.models.usert_directory_path),
        ),
    ]
