# Generated by Django 3.1.7 on 2021-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210411_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='cdefault', upload_to='courses'),
        ),
    ]
